### ISSUE TITLE
启动失败了

### ISSUE THREAD

**Issue by tinterking** [dreamrover/bigrats-go#1]
大神你好，我在搜索硕鼠时发现了你的文章，找到这并下载了 你编译好的这个bigrats-go
不好意思，因为我不太了解编程这块，导致不会查看错误原因，但是又很想用你这个软件，所以在这里提问一下，希望你不要介意。

我在终端运行时出现了
./bigrats: /usr/lib/x86_64-linux-gnu/libQt5PrintSupport.so.5: version `Qt_5' not found (required by /usr/lib/x86_64-linux-gnu/libqtdrv.ui.so.1)
./bigrats: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by /usr/lib/x86_64-linux-gnu/libqtdrv.ui.so.1)
./bigrats: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5: version `Qt_5' not found (required by /usr/lib/x86_64-linux-gnu/libqtdrv.ui.so.1)
./bigrats: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.7' not found (required by /usr/lib/x86_64-linux-gnu/libqtdrv.ui.so.1)
./bigrats: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5' not found (required by /usr/lib/x86_64-linux-gnu/libqtdrv.ui.so.1)
希望你在有空时可以恢复一下，感激不尽 。麻烦了

**Comment by dreamrover** [comment]
> 大神你好，我在搜索硕鼠时发现了你的文章，找到这并下载了 你编译好的这个bigrats-go
> 不好意思，因为我不太了解编程这块，导致不会查看错误原因，但是又很想用你这个软件，所以在这里提问一下，希望你不要介意。
> 
> 我在终端运行时出现了
> ./bigrats: /usr/lib/x86_64-linux-gnu/libQt5PrintSupport.so.5: version `Qt_5' not found (required by /usr/lib/x86_64-linux-gnu/libqtdrv.ui.so.1) ./bigrats: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by /usr/lib/x86_64-linux-gnu/libqtdrv.ui.so.1)
> ./bigrats: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5: version `Qt_5' not found (required by /usr/lib/x86_64-linux-gnu/libqtdrv.ui.so.1) ./bigrats: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.7' not found (required by /usr/lib/x86_64-linux-gnu/libqtdrv.ui.so.1)
> ./bigrats: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5' not found (required by /usr/lib/x86_64-linux-gnu/libqtdrv.ui.so.1)
> 希望你在有空时可以恢复一下，感激不尽 。麻烦了

感谢提issue，实在抱歉现在才看到……不知道你还需要吗。你应该是没有按照步骤2中安装Qt5运行时环境，或者是安装的Qt版本不匹配，不知道你用的是哪个Linux发行版？

**Comment by tinterking** [comment]
哇，终于恢复了，先谢谢愿意为我解决问题哈哈。 我用的是ubuntu16.04lts，我当时用不了然后就被我删了，不过我好安装过你的之前的版本，应该是qt5库没装全我不知道该装哪些，然后就是firefox我按照你那个方法一直没有弄出来，后来没人教鼓捣了一会就放弃了，还是蛮遗憾的，不过这次回复我了可以帮我解决一下问题吗，感激不尽，先谢谢你了

**Comment by dreamrover** [comment]
我当时是在Debian 8 x86_64下开发的，还真没在Ubuntu上试过，也可能是Qt的版本不匹配和我编译环境的版本不匹配，我这几天抽空弄个Ubuntu试试，而且现在的Firefox更新比较大，可能要换个方法配置Firefox，我一起看看。我自己也很久没用这个软件了哈哈哈 :-P

**Comment by tinterking** [comment]
> 我当时是在Debian 8 x86_64下开发的，还真没在Ubuntu上试过，也可能是Qt的版本不匹配和我编译环境的版本不匹配，我这几天抽空弄个Ubuntu试试，而且现在的Firefox更新比较大，可能要换个方法配置Firefox，我一起看看。我自己也很久没用这个软件了哈哈哈 :-P

那先说声辛苦了，期待可以早日使用！（慢慢来，不急）

**Comment by dreamrover** [comment]
> > 我当时是在Debian 8 x86_64下开发的，还真没在Ubuntu上试过，也可能是Qt的版本不匹配和我编译环境的版本不匹配，我这几天抽空弄个Ubuntu试试，而且现在的Firefox更新比较大，可能要换个方法配置Firefox，我一起看看。我自己也很久没用这个软件了哈哈哈 :-P
> 
> 那先说声辛苦了，期待可以早日使用！（慢慢来，不急）

在Ubuntu 18.04 x86_64上弄成功了，在release里发了一版，你按照Wiki里的说明弄一下试试，不要按照readme里的，readme还没更新。
[https://github.com/dreamrover/bigrats-go/wiki/Install-Bigrats-on-Ubuntu](https://github.com/dreamrover/bigrats-go/wiki/Install-Bigrats-on-Ubuntu)

**Comment by tinterking** [comment]
> > > 我当时是在Debian 8 x86_64下开发的，还真没在Ubuntu上试过，也可能是Qt的版本不匹配和我编译环境的版本不匹配，我这几天抽空弄个Ubuntu试试，而且现在的Firefox更新比较大，可能要换个方法配置Firefox，我一起看看。我自己也很久没用这个软件了哈哈哈 :-P
> > 
> > 
> > 那先说声辛苦了，期待可以早日使用！（慢慢来，不急）
> 
> 在Ubuntu 18.04 x86_64上弄成功了，在release里发了一版，你按照Wiki里的说明弄一下试试，不要按照readme里的，readme还没更新。
> https://github.com/dreamrover/bigrats-go/wiki/Install-Bigrats-on-Ubuntu

你好，还是有点问题搞了一会儿还是不太明白，我想问一下，就是我现在全部都装好了，下载的方法是点击硕鼠专用链下载然后选择nano下载？我点击之后发现不跳转，然后我试着打开bigrat发现直接按图标打不开，只有在终端下才能打开，这是什么情况呢？不好意思又麻烦你了

**Comment by dreamrover** [comment]
点“硕鼠专用下载”，不跳转可能是因为handler.json里没加对，注意"bigrats:{...}"的前面还有个逗号，修改之后要重启Firefox，然后看看preference——applications里面是不是多了bigrats一项，action里是不是bigrats可执行文件。bigrats只要有可执行权限双击就能打开啊，或者你双击Bigrats.desktop试试，在弹出框里点“信任并运行”，应该就能启动，图标也会变成小老鼠。
如果还是有问题的话继续提，不要客气，我也希望这个工具能帮到更多的人。
