### ISSUE TITLE
关于硕鼠下载

### ISSUE THREAD

**Issue by south55** [dreamrover/bigrats-go#2]
hi 前辈
我项目上有网站视频下载的任务，你这边能做类似硕鼠这样的下载功能吗，linux版本的

**Comment by dreamrover** [comment]
> hi 前辈
> 我项目上有网站视频下载的任务，你这边能做类似硕鼠这样的下载功能吗，linux版本的

抱歉现在才看到……看了你的主页不知道是哪个项目？现在还在做吗？
