### ISSUE TITLE
handlers.json

### ISSUE THREAD

**Issue by DarwinChe** [dreamrover/bigrats-go#3]
in my version of firefox, mimetype.rdf doesnot work, the thing that controls mime is handlers.json

**Comment by dreamrover** [comment]
> in my version of firefox, mimetype.rdf doesnot work, the thing that controls mime is handlers.json

Which version of Firefox are you using? When I developed this tool Firefox was in an old version compared to current version. And it had a huge update about one year ago which may caused the problem. I will look into this recently.

**Comment by dreamrover** [comment]
I've solved this problem. Please refer to:
[https://github.com/dreamrover/bigrats-go/wiki/Install-Bigrats-on-Ubuntu](https://github.com/dreamrover/bigrats-go/wiki/Install-Bigrats-on-Ubuntu)
or 
[https://github.com/dreamrover/bigrats-go/wiki/Install-Bigrats-on-Debian](https://github.com/dreamrover/bigrats-go/wiki/Install-Bigrats-on-Debian)

**Comment by DarwinChe** [comment]
thanks, it works now!

**Comment by DarwinChe** [comment]
how do you find out about docs on handlers.json, I wondered?

**Comment by dreamrover** [comment]
> how do you find out about docs on handlers.json, I wondered?

I just guessed.... by analyzing the json file format :-P

**Comment by DarwinChe** [comment]
you are really smart, so nice to meet you, and this is a good tool to use
